### ISSUE TITLE
onClick of  Not Yet Started, In Progress, Achieved, and Broken, corresponding list is displayed.

### ISSUE THREAD

**Issue by VirenMohindra** [TrumpTracker/trumptracker.github.io#40] opened 2016-11-16 07:16 UTC
![screen shot 2016-11-16 at 2 15 37 am](https://cloud.githubusercontent.com/assets/10460518/20338036/93384388-aba2-11e6-9aa3-4dc2764e102f.jpg)

**Comment by VirenMohindra** [comment] 2016-11-16 13:21
Definitely want to move this to v3.0, since this isn't a priority.

**Comment by ek68794998** [comment] 2017-01-24 00:40
Looks like a duplicate of this was created at #83. Is v3 still in the works?

**Comment by VirenMohindra** [comment] 2017-01-24 05:53
@ekumlin yes it is

**Closed as completed** 2017-01-24 06:04 UTC
Labels: enhancement
